services:
    postgres:
        image: postgres:18.2-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        container_name: postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - plutus-network

volumes:
    postgres_data:

networks:
    plutus-network:
        driver: bridge
